### ISSUE TITLE
Porting WEASEL 2.0 to pyts

### ISSUE THREAD

**Issue by aglenis** [patrickzib/dictionary#4]
I am cross-posting this issue here.
I am trying to port WEASEL 2.0 to pyts but I have problems achieving comparable accuracy using pyts.
I don't know if this is because of a bug in the implementation or because of wrong hyper-parameters tuning.
Here is the pyts issue : https://github.com/johannfaouzi/pyts/issues/155
Thanks in advance

**Comment by patrickzib** [comment]
Thank you for bringing it up and porting WEASEL 2.0! I will have a look within the next days what could be wrong about it.

**Comment by patrickzib** [comment]
I am closing this for now, as there is an issue in pyts.
